#include <switch/result.h>

#define MIIPORT_MOUDLE 421

#define UNSUPPORTED_EXT   MAKERESULT(MIIPORT_MOUDLE,0)
#define NO_QR             MAKERESULT(MIIPORT_MOUDLE,1)
#define QR_DECODE_FAIL    MAKERESULT(MIIPORT_MOUDLE,2)
#define JPEG_DECODE_FAIL  MAKERESULT(MIIPORT_MOUDLE,3)
#define AES_CCM_FAILED    MAKERESULT(MIIPORT_MOUDLE,4)
#define SHOWING_POPUP     MAKERESULT(MIIPORT_MOUDLE,5)